defaults:
  - base_config

replan_step: 20
base_url: http://localhost:9500
use_delta: true
action_ensemble_horizon: 7
adaptive_ensemble_alpha: 0.1
action_ensemble: false

output_dir: ./result_simpler_grok-4